### ISSUE TITLE
No server running...

### ISSUE THREAD

**Issue by SeanPedersen** [fileverse/fileverse-ddoc#175]
Just cloned the repo and installed using `$ npm ci`

Then tried to run the server: `$ npm run dev`
Which seemed to work:

```
> @fileverse-dev/ddoc@2.0.9-patch-11 dev
> vite

The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.4.9  ready in 664 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

BUT no server running on http://localhost:5173/ ...
Any idea?

**Comment by mbj36** [comment]
@SeanPedersen Please `cd` into `demo` folder, install dependencies and run the vite server

We will update the documentation in coming weeks
